name: Deploy Infrastructure and Application to Netlify

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- INFRASTRUCTURE PHASE ---

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          # This is the non-interactive login step!
          # It uses your secret to create the authentication configuration for Terraform.
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Now Terraform is authenticated and can talk to your HCP Terraform backend.
      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve 

      - name: Get Netlify Site ID
        id: get_site_id
        run: |
          SITE_ID=$(terraform output -raw site_id)
          echo "NETLIFY_SITE_ID=$SITE_ID" >> $GITHUB_ENV
      
      # --- APPLICATION PHASE (no changes here) ---

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ env.NETLIFY_SITE_ID }}
